Devolutions/sspi-rs

src/sspi/internal/credssp.rs
This pull request fixes Windows 7 connection problems for IronRDP clients.
=> Add TS Request version to client and server

Cargo.toml, src/sspi/kerberos/client/generators.rs
Tested with multiple combinations of username and domain information, it makes UPN + empty domain work.
=> Fix Kerberos name type and realm

Cargo.toml, ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj, src/dns.rs, src/kdc.rs, src/lib.rs, src/sspi/kerberos/client/generators.rs, src/sspi/negotiate.rs, src/utils.rs
Implement DNS SRV querying with Windows DnsQuery APIs
Implement Windows KDC detection from registry keys
Implement Windows DNS name server detection from registry keys
Improve trust-dns name server detection and SRV record processing
=> Add Windows-specific KDC detection with registry and DNS SRV records

ffi/src/credentials_attributes.rs, ffi/src/sec_handle.rs, ffi/src/sec_winnt_auth_identity.rs, src/sspi/negotiate.rs
Update to match https://github.com/FreeRDP/FreeRDP/pull/8274
=> Accept SEC_WINNT_AUTH_IDENTITY_EX.PackageList in AcquireCredentialsHandle

ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj, src/kdc.rs, src/krb.rs, src/lib.rs
- Add krb5.conf file parser
- Find krb5.config file paths
- Use krb5.conf for KDC detection
=> Add KDC detection using krb5.conf config file parser

src/kdc.rs, src/sspi/negotiate.rs, src/sspi/pku2u.rs, src/utils.rs
=> Fix compilation on non-Windows platforms

Cargo.toml, ffi/Cargo.toml, ffi/src/common.rs, ffi/src/debug.rs, ffi/src/lib.rs, ffi/src/macros.rs, ffi/src/sec_handle.rs, ffi/src/sec_pkg_info.rs, ffi/src/sec_winnt_auth_identity.rs, ffi/src/security_tables.rs, src/sspi/ntlm/messages/computations.rs, src/sspi/winapi.rs
This is behind a compile-time feature flag called `debug_mode`.
=> Add logging infrastructure for debugging-purposes

Cargo.toml, src/sspi/internal/credssp.rs, src/sspi/kerberos/config.rs, src/sspi/negotiate.rs, src/sspi/ntlm.rs, src/sspi/ntlm/messages/computations/test.rs, src/sspi/pku2u/config.rs
I made `CredSspClient` satisfy `Send` trait and added a unit test that checks if the trait bound is implemented for `CredSspClient`.
=> Make `CredSspClient` satisfy `Send` trait

src/pku2u/cert_utils/win_extraction.rs
The  `winapi` crate has string literals without the NULL terminator and we haven't handled this case. It was lucky to extract a private key sometimes when there were zeros after the sting in memory.
=> PKU2U: Fix a private key of a certificate extraction

fuzz/fuzz_targets/fuzz_ts_request.rs, src/ber/mod.rs
=> Fix falling `fuzz_ts_request` fuzz test

Cargo.toml, src/credssp/sspi_cred_ssp/mod.rs, src/kerberos/mod.rs, src/lib.rs, src/negotiate.rs, src/pku2u/cert_utils/validation.rs, src/pku2u/generators.rs, src/utils.rs
=> fix(sspi-rs): Improve mapping Kerberos errors into SSPI errors

src/ntlm/mod.rs, src/ntlm/test.rs
These tests started to fall at some point and thus have been marked as ignored. I fixed the tests and removed the ignore filter.
=> fix(ntlm): Fixed falling ignored tests

ffi/src/credentials_attributes.rs, ffi/src/sec_handle.rs, src/negotiate.rs
This PR fixes issues with _Kerberos_ that Richard has faced. 
- Remove using of `SecPkgCredentialsKdcProxySettingsA` as _Microsoft_ doesn't have this structure and uses `SecPkgCredentialsKdcProxySettingsW`even for _ANSI_ functions. This fixes setting _KdcProxy_ URL on non-_Windows_ machines. 
- Add setting of the hostname in _Kerberos_ config when it's initialized from environment variables.
=> Kerberos fixes

examples/kerberos.rs
Fix compile error for Kerberos  example
=> Tiny Updates For Kerbero Example 

Cargo.lock, Cargo.toml
Prepare for publishing next version
=> chore(version): prepare for 0.11.0

.github/workflows/ci.yml, src/generator.rs, src/kerberos/mod.rs, src/negotiate.rs, src/pk_init.rs
This patch fixes the build for the scard feature and modify the CI to check we don’t mistakenly break it again in the future.
=> fix: build failure for scard feature

src/network_client.rs
The HTTP client was ignoring the status code of the HTTP response received from the KDC proxy (e.g.: Devolutions Gateway), and returned an empty payload, resulting in the "TruncatedData" error.
=> fix(kdc): catch KDC proxy HTTP status error

tools/aadjoin/AADJoin/AADJoin.csproj
Address the following Dependabot alerts : 
https://github.com/Devolutions/sspi-rs/security/dependabot/7
https://github.com/Devolutions/sspi-rs/security/dependabot/8
=> build(deps): update System.IdentityModel.Tokens.JWT to 6.35.0

Cargo.lock, crates/ffi-types/src/common.rs, crates/winscard/Cargo.toml, crates/winscard/src/lib.rs, crates/winscard/src/scard.rs, crates/winscard/src/scard_context.rs, crates/winscard/src/winscard.rs, ffi/Cargo.toml, ffi/src/winscard/scard.rs, ffi/src/winscard/scard_context.rs
Hi,
In this PR, I improved the `crates/winscard` crate. I didn't change the emulated smart card implementation a lot. Basically, I just added new methods to the `WinScard` and `WinScardContext` traits and implemented them for the emulated smart card.
Some of these changes may seem unnecessary but I need them to provide better system-provided smart cards support. Feel free to ask any questions regarding these changes.
_Note. I think I'll be better to squash and merge this PR._
=> Winscard improvements

ffi/src/sspi/common.rs, ffi/src/sspi/sec_pkg_info.rs, ffi/src/sspi/sec_winnt_auth_identity.rs, ffi/src/utils.rs
Hi,
In this PR, I've fixed some UB and memory leaks I found using [Miri](https://github.com/rust-lang/miri).
=> Fix UB and memory leaks found by Miri

.github/workflows/ci.yml
=> ci(test): run FFI tests using Miri

Cargo.lock, Cargo.toml, crates/winscard/Cargo.toml, ffi/Cargo.toml
Hi,
We added new dependencies to the `sspi-ffi` crate in previous PRs and I decided to finally introduce workspace dependencies.
=> chore(deps): introduce workspace dependencies;

Cargo.lock, Cargo.toml, crates/winscard/Cargo.toml, ffi/Cargo.toml, ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
- sspi -> 0.14.0
- winscard -> 0.2.1
- Devolutions.Sspi -> 2024.10.8.0
=> chore(release): prepare publishing

Cargo.lock, Cargo.toml
=> chore(release): prepare for sspi v0.14.1

Cargo.lock, Cargo.toml, src/dns.rs
=> chore(release): prepare for sspi v0.15.0

.github/workflows/build-native.yml, ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
Also prepare a new release of the NuGet library.
- Devolutions.Sspi -> 2024.12.9.0
=> build: support 16 KB page sizes on Android

src/kerberos/client/generators.rs, src/kerberos/mod.rs
Hi,
I added the `USE_DCE_STYLE` flag support. It is related to #121 
I change the target branch when #357 is merged.
=> feat(sspi): add `USE_DCE_STYLE` flag support

Cargo.lock, Cargo.toml, crates/dpapi-cli-client/Cargo.toml, crates/dpapi-cli-client/src/cli.rs, crates/dpapi-cli-client/src/logging.rs, crates/dpapi-cli-client/src/main.rs, crates/dpapi/src/client.rs
Hi,
I implemented a simple DPAPI client for secret encryption and decryption.
This app will be used for blob decryption/encryption and DPAPI implementation testing (by QAs).
=> feat(dpapi-cli): implement simple DPAPI cli client;

crates/dpapi-core/Cargo.toml, crates/dpapi-fuzzing/Cargo.toml, crates/dpapi-native-transport/Cargo.toml, crates/dpapi-pdu/Cargo.toml, crates/dpapi-transport/Cargo.toml, crates/dpapi-web/Cargo.toml
dpapi crates are not yet ready.
=> chore: explicitely set publish = false for some crates

.github/dependabot.yml, Cargo.lock, Cargo.toml, src/dns.rs, src/kdc.rs
I had some time between reviews. I scrolled through issues and decided to quickly fix #347.
closes #347
=> feat(sspi): migrate from `winreg` to `windows-registry` crate

src/negotiate.rs
=> fix: Negotiate attempts KDC detection even when Kerberos is disabled

.github/workflows/build-native.yml, Cargo.lock, Cargo.toml, ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
Aim for good balance between size and performance.
- Baseline: 19M
- After: 8.9M
=> build: optimize binary size for FFI builds
