Devolutions/sspi-rs

- src/sspi/ntlm.rs
- src/sspi/ntlm/messages/computations/test.rs
Empty password is allowed, for example in rdp
> add the ability to use a credentials with empty password in ntlm

- src/sspi/internal/credssp.rs
- src/sspi/internal/credssp/ts_request.rs
This PR fixes an issue with using NLA with servers that are not updated to support CredSSP v6. 
If the CredSSP version mismatches in the `TSRequest`, what happens with the old code is that we start with v6 for the first request, then as we get the reply with v5 all consecutive reply from us have v5 set (this is caused by `ts_request_version` being set to None). The other side will thread this as an error and close the connection.
By explicitly setting `ts_request_version` to a specific version we make sure that our side's version remains consistent through the exchange and avoid erroring when the versions mismatch (tested with W2008 that uses v5, it fixes the issue).
> Fix CredSSP version mismatch crash.

- Cargo.toml
- src/sspi/internal/credssp.rs
- src/sspi/kerberos.rs
- src/sspi/kerberos/client/generators.rs
- src/sspi/kerberos/network_client.rs
I'm working on integrating the latest changes of sspi-rs in IronRDP. It turned out that some things were missing in sspi-rs to make it works, so this PR fixes it. 
I added the `setting` service principal name in `CredSspClient`.
Also, I made some KdcProxy related code fixes:
-  Add missing reqwest `rustls` feature for TLS establishing.
- Add missing `KdbProxyMessage` generation in `ReqwestNetworkClient::send_http`.
> Add setting SPN in CredSspClient and some KdcProxy code fixes

- c-api/build.rs
Compilation fix for https://github.com/Devolutions/sspi-rs/pull/21 on Windows
> use /FORCE:MULTIPLE to workaround symbol conflict on Windows

- c-api/src/common.rs
- c-api/src/lib.rs
- c-api/src/macros.rs
- c-api/src/sec_buffer.rs
- c-api/src/sec_handle.rs
- c-api/src/sec_pkg_info.rs
- c-api/src/sec_winnt_auth_identity.rs
- c-api/src/utils.rs
- c-api/sspi.def
- src/sspi/negotiate.rs
- src/sspi/ntlm.rs
C# _NegotiateStream_ calls _SSPI_ to make an authentication. If  _NegotiateStream_ uses sspi-rs as the _SSPI_ module, authentication will fail because of some issues and not implemented things in sspi-rs. This PR fixes it.
Improvements:
- Added an implementation of the _Negotiate_ structure for a server (`accept_security_context_impl` function).
- Added an explicit calling to the complete_auth_token if there wasn't one before.  To fully complete _NTLM_ authentication, the user needs to call the `complete_auth_token` function, but _NegotiateStream_ doesn't call it. 
- Added support for _SECPKG_ATTR_NEGOTIATION_INFO_ attribute in _QueryContextAttributesA/W_. _NegotiateStream_ needs it.
- Fixed context attributes. So far _NTLM_ and other implemented security packages didn't care about …
> C# NegotiateStream fixes

- Cargo.toml
- src/crypto.rs
- src/sspi.rs
- src/sspi/channel_bindings.rs
- src/sspi/kerberos.rs
- src/sspi/kerberos/client/extractors.rs
- src/sspi/kerberos/client/generators.rs
- src/sspi/ntlm.rs
- src/sspi/ntlm/messages/client/authenticate.rs
- src/sspi/ntlm/messages/computations.rs
- src/sspi/ntlm/messages/computations/test.rs
- src/sspi/ntlm/messages/server/authenticate.rs
I added support of the security channel bindings. Basically, the channel bindings are an md5 checksum of the token that is used to prevent MITM attacks.
1. In the case of the NTLM, this checksum is transferred as special AvPair (AvPair::ChannelBindings).
2. In the case of the Kerberos, it is transferred as a part of the checksum in the authenticator during the AP exchange. 
The token for md5 checksum calculation passed into our library as the SecurityBuffer with the type SECBUFFER_CHANNEL_BINDINGS.
References:
- https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/extended-protection-for-authentication-overview
- https://docs.microsoft.com/en-us/windows/win32/api/sspi/ns-sspi-sec_channel_bindings
- https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-N …
> SECBUFFER_CHANNEL_BINDINGS support

- Cargo.toml
- src/sspi/kerberos/config.rs
- src/sspi/kerberos/network_client.rs
cc @RRRadicalEdward 
Introduction of a field with the type `Box<dyn NetworkClient>` caused all wrapping structs to be non-`Send`ables. This is breaking and probably not desirable (this notably breaks Devolutions Gateway code).
Other breaking changes were introduced in version starting 0.3.3 and up to 0.3.6, the most obvious one being the `CredSspClient::new` function which now has 5 parameters instead of 3.
For this reason, I yanked all these versions and this PR bumps the version to 0.4.0.
> fix: structs not implementing Send trait

- Cargo.toml
- ffi/src/sec_pkg_info.rs
- src/sspi.rs
- src/sspi/kerberos.rs
- src/sspi/kerberos/client/extractors.rs
- src/sspi/kerberos/client/generators.rs
- src/sspi/kerberos/client/mod.rs
- src/sspi/kerberos/encryption_params.rs
- src/sspi/kerberos/server/extractors.rs
- src/sspi/kerberos/utils.rs
Hi! This PR replaces the `kerberos-crypto` and `kerberos-constants` crates the `picky-krb` Kerberos crypto implementation.
> Replace kerberos_crypto with picky-krb Kerberos crypto

- .github/workflows/nuget.yml
I'd like to modify this to use the current date instead, but then I'm unsure how to deal with multiple releases per day.
> Fix version number parsing

- Cargo.toml
- src/sspi/kerberos/client/generators.rs
sys_info::hostname() calls hostname.exe on Windows, while whoami::hostname() calls the Win32 APIs. We had some calls to whoami::hostname() in some places already, and sys_info::hostname() was the only reason to import the sys_info crate.
> replace sys_info::hostname by whoami::hostname

- .github/workflows/nuget.yml
- .gitignore
- Info.plist
- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.targets
Fix Android packaging to properly reference the native libraries in the final build
Add a universal build for iOS, and wrap the resulting .dylib in a framework bundle. Although universal builds are not needed for our case (RDM only supports arm64), it's simpler to just re-use the macOS step. There is no extra cost to this as the iOS application build strips unsupported ABIs from the final .app.
I'm unable to test the iOS changes as a VS issue is preventing me from installing local nuget packages; however the Android changes should be fine. If there is an issue with the iOS package I'll iterate further.
> Android and iOS packaging

- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.targets
Prevent iOS builds from trying to link the macOS library
> Fix linkage in nuget package

- Cargo.toml
- ffi/src/credentials_attributes.rs
- ffi/src/sec_handle.rs
- src/dns.rs
- src/kdc.rs
- src/krb.rs
- src/sspi/kerberos.rs
- src/sspi/negotiate.rs
`trust-dns` resolver won't work on iOS; it tries to read configuration from `/etc/resolv.conf`. Even if iOS uses this path itself, it won't be readable by us as it's outside the application sandbox.
`dnssd` is available since iOS 10; so just switch to use the same code paths as macOS.
Check the individual commits as there was some churn from running `cargo fmt`.
> Use dns-sd on iOS

- src/dns.rs
`trust-dns` [can't configure itself on Android](https://github.com/bluejekyll/trust-dns/issues/652).
As a workaround, accept a comma-separated list of DNS servers via the `SSPI_DNS_URL` environment variable and use them to create the resolver config.
> Fall back to obtaining DNS servers from environment

- src/sspi/kerberos.rs
- src/sspi/kerberos/client/generators.rs
- Removed a hardcoded hostname
- Turn on preauthentication
> Kerberos authentication fixes 

- ffi/src/debug.rs
- ffi/src/security_tables.rs
The `SSPI_DBG_LOG_PATH` environment variable can be used to specify the log file.
An FFI function `RustSspiSetupLogger` is provided in order to manually setup the logger.
> fix(ffi): improve debugging infrastructure

- .github/workflows/build-native.yml
- .github/workflows/ci.yml
- .github/workflows/nuget.yml
- Cargo.toml
- ffi/Cargo.toml
- ffi/src/credentials_attributes.rs
- ffi/src/sec_handle.rs
- rust-toolchain.toml
- src/dns.rs
- src/sspi.rs
- src/sspi/ntlm/test.rs
The `build-native` and `build-universal` steps of nuget.yml are broken out into a new workflow (build-native.yml). I added an extra matrix element for "build type" - release and debug (with the debug build enabling the `debug_mode` feature).
There is no debug nuget package produced - the debug artifacts are simply too large. However the libraries are all available as artifacts for debugging and dev.
I added a CI workflow to be called from PRs on `master`. It has the same basic steps as IronRDP (formatting, lints, tests) as well as calling the `build-native` workflow. We can validate native build on all platforms at integration time.
Additionally, I disabled failing tests (including one doc test), refactored suggestions by clippy and fixed deprecation warnings in the workflow(s).
> CI build and checks, refactor workflows

- ffi/src/common.rs
- ffi/src/sec_buffer.rs
- ffi/src/sec_handle.rs
Add support for output buffer memory allocation in InitializeSecurityContext when the ISC_REQ_ALLOCATE_MEMORY flag is passed. The buffer has to be freed using FreeContextBuffer, and while we already have such a function, the drop_in_place() call likely didn't do anything on a void pointer. This means we've been leaking memory, so I've just commented out the call to free memory inside FreeContextBuffer, and we'll need to review buffer memory allocation/release in the SSPI API to properly handle all cases, and avoid freeing memory incorrectly.
> add output buffer memory allocation

- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
- src/dns.rs
- src/sspi.rs
I also inverted the order in `get_trust_dns_resolver`. The "SSPI_DNS_URL" variable is checked first - this lets us override the system_conf more easily for testing (on systems that support it).
> Fix regression in dns module

- src/sspi/kerberos.rs
WSMan/WinRM calls EncryptMessage/DecryptMessage more times than CredSSP does, so we've hit a condition where the internal Kerberos state was incorrectly rejecting the calls.
> Fix Kerberos EncryptMessage

- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.targets
The ios-net6 build system packages _any_ dylibs it finds in the runtimes path, regardless of if they are referenced by the project build. This causes an issue for App Store uploads, where a dylib cannot be included in the final application bundle directly.
Since we aren't actually using the standalone .dylibs for iOS, I just remove them from the package.
Additionally, make some fixes for clarity in the .targets file.
> fix(ffi): Fix ios-net6 package issues

- .github/workflows/ci.yml
- ffi/build.rs
On Windows, we rename symbols using a .def file.
For that, we emit a cargo instruction.
> cargo:rustc-link-arg=/DEF:sspi.def
However, when attempting to run unit tests this causes an error.
```
Caused by:
could not execute process `<redacted>` (never executed)
Caused by:
%1 is not a valid Win32 application. (os error 193)
```
There is currently no built-in way to check if cargo is going to run the tests from the build.rs itself:
https://github.com/rust-lang/cargo/issues/4001
This commit adds a new environment variable that when set prevent the instruction emission.
> ci: fix sspi-ffi test job for Windows

- src/kerberos/mod.rs
- src/pku2u/mod.rs
This PR adds support for _SECBUFFER_STREAM_. See https://github.com/Devolutions/sspi-rs/issues/84 for more information.
> Add support for SECBUFFER_STREAM on DecryptMessage

- ffi/src/sec_handle.rs
- ffi/src/sec_winnt_auth_identity.rs
This PR fixes an authentication error that happens when performing _Windows 11_  -> _Windows 10_ `RDP` connection.
> fix(ffi(tsssp)): split auth_data_to_identity_buffers function into A and W ones

- src/dns.rs
Makes it possible to call the MacOS version of dns_query_srv_records() from an existing tokio runtime.
> fixes dns_query_srv_records() for MacOS

- src/credssp/mod.rs
`MUTUAL_AUTH` and `USE_SESSION_KEY` flags are needed for the `Kerberos` protocol to construct correct `ApReq` options
> fix(sspi(credssp)): fix context requirements

- ffi/src/logging.rs
We probably want to create the file if it doesn’t already exist.
> fix(ffi): create log file if it does not exist

- ffi/src/common.rs
- ffi/src/sec_handle.rs
- ffi/src/sec_pkg_info.rs
Updated fix from https://github.com/Devolutions/sspi-rs/pull/124 to use u32 instead of c_uint, which guarantees us that an unsigned integer of 32-bit, same as ULONG on Windows. We aim to keep ABI stability with the SSPI API as if on Windows, and ULONG on Windows is always 32-bit, unlike "unsigned long" which can be 64-bit on non-Windows. This is just the updated fix, I will need to make a second pass to eliminate *all* usage of c_ulong in the current SSPI FFI, as there are many others that could explain why MemorySanitizer is still complaining when using sspi-rs in FreeRDP.
> fix stack corruption on decrypt message

- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
- src/kerberos/client/generators.rs
- src/kerberos/mod.rs
KRB5 U2U (1.2.840.113554.1.2.2.3) requires the use-session-key flag, but FreeRDP doesn't explicitly set ISC_REQ_USE_SESSION_KEY in the InitializeSecurityContext flags. mstsc always sets ISC_REQ_USE_SESSION_KEY, but also always selects KRB5 U2U. With FreeRDP + Windows SSPI, it looks like setting ISC_REQ_USE_SESSION_KEY forces KRB5 U2U, while not setting it defaults to regular Kerberos. The FreeRDP WinPR Kerberos implementation sets the use-session-key flag based on the negotiated mech id (U2U or not) rather than expect the ISC_REQ_USE_SESSION_KEY flag to be passed to the Negotiate module. We're going for a similar fix on our side, and I suspect we may only support KRB5 U2U at this point anyway.
> Fix usage of Kerberos use-session-key flag with KRB5 U2U

- ffi/src/sec_handle.rs
- src/kerberos/config.rs
- src/kerberos/mod.rs
- src/negotiate.rs
- src/network_client.rs
- src/ntlm/messages/client/authenticate.rs
- src/ntlm/messages/client/challenge.rs
- src/ntlm/messages/server/authenticate.rs
- src/ntlm/messages/server/challenge.rs
- src/ntlm/messages/server/complete_authenticate.rs
- tools/wasm-testcompile/src/lib.rs
Refactored `NetworkClient` API as required by https://github.com/Devolutions/IronRDP/issues/155#issuecomment-1593724348
- Added the `NetworkClient::supported_protocols` method to discover if the underlying network client implementation supports the given protocol
- Added the `NetworkClient::name` method to provide more context for the error messages
- Moved ASN.1 messages serialization/deserialization for `NetworkClient::send_http` from implementors to sspi-rs internal code.
- Removed `NetworkClient::send_http` and squashed it to single`NetworkClient::send` (now a signature for all tcp/udp/http/https methods is the same)
> refactor(network_client): Refactor NetworkClient trait

- ffi/src/common.rs
- ffi/src/sec_buffer.rs
- ffi/src/sec_pkg_info.rs
- tools/sspi-ffi-attacker/Cargo.toml
- tools/sspi-ffi-attacker/src/attack.rs
- tools/sspi-ffi-attacker/src/main.rs
The `FreeContextBuffer` function is using `Box::<T>::from_raw` to free
memory from a raw pointer of type `*mut c_void`. Sadly, this is unsound.
Indeed, knowledge of the original type is required when deallocating memory in
Rust. At the bare minimum, knowledge of the original type’s `Layout` is required
since this information is required by the default global allocator (actually
it is a safety invariant of [_any_ global allocator](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html) in Rust).
The correct layout for a given type can easily be retrieved by using
`Layout::new::<T>` or `Layout::for_value::<T>`, but this requires knowledge of
the concrete type `T`. That’s why `Box::<T>::from_raw` safety invariant is defined
as follows:
> For non-zero-sized values, a ``Box`` will use the …
> fix(ffi): unsound FreeContextBuffer

- Cargo.toml
- src/dns.rs
`trust_dns_resolver` is implemented using async Rust and the tokio runtime. Its blocking API is creating a new tokio runtime internally, this is a problem because tokio does not allow starting a runtime from within another runtime (panic).
> fix: reentrant tokio runtime when using Resolver

- src/lib.rs
- src/smartcard.rs
Hi,
In this PR I've added a Kerberos smart card module. This module can communicate with the real smart card using the WinSCard API to sign some data.
You can notice that the code contains a lot of hardcoded values like input buffers for the `SCardTransmit` function, control code for the `SCardControl` function, etc. At the current moment, we do not have any APDU command builder or anything else. So, we are forced to use hardcoded values. I think, when I implement the second phase (iteration) we'll be able to reuse some code and refactor this module.
How I know what APDU command to use:
I recorded API calls and extracted needed APDUs for the data signing.
_Note_: It doesn't contain actual smart card logon implementation. I'll open a separate PR for it.
Docs & references:
* [`winscard.h` …
> Kerberos smart card module

- src/credssp/mod.rs
- src/credssp/sspi_cred_ssp/mod.rs
- src/credssp/sspi_cred_ssp/tls_connection.rs
- src/dns.rs
- src/kerberos/client/extractors.rs
- src/kerberos/client/generators.rs
- src/kerberos/mod.rs
- src/lib.rs
- src/network_client.rs
- src/pku2u/cert_utils/win_extraction.rs
- src/pku2u/macros.rs
- src/utils.rs
I revisited a bunch of places where `sspi-rs` returns `ErrorKind::InternalError` and changed them to return more meaningful and proper errors.
> refac(sspi): return proper SSPI error

- src/credssp/sspi_cred_ssp/mod.rs
Add SSLKEYLOGFILE support in sspi-rs when injected in mstsc.exe, allowing live Wireshark decryption [in the same fashion as IronRDP.](https://github.com/awakecoding/wireshark-rdp)
> add SSLKEYLOGFILE support

- ffi/src/lib.rs
- ffi/src/sec_winnt_auth_identity.rs
- ffi/src/utils.rs
Hi,
I fixed the UPN (user principal name) handling. closes #150 
The problem was in the trailing null characters at the end of the username buffer. In the case of UPN logon, the username buffer has two null bytes at the end.
Also, I recorded a little video demonstration:
* logon using UPN
https://github.com/Devolutions/sspi-rs/assets/43034350/1d3f99be-4d99-4cc4-8a9d-d01f19ac969b
* logon using domain + username
https://github.com/Devolutions/sspi-rs/assets/43034350/ec4ef518-6fca-487b-a35f-1f14dd9aac35
cc @awakecoding
> Fix UPN handling

- ffi/Cargo.toml
- ffi/src/sec_winnt_auth_identity.rs
Hi, I wrote a fix for the #152 issue.
When we try to connect using the `mstsc` we have two options for the source of the credentials: enter them manually or `mstsc` will use the saved credentials. The `mstsc` passes the `CredsspSubmitBufferBothOld` (51) only when we try to log in using the saved credentials. Moreover, it also sets the `credssp_cred.p_spnego_cred` pointer to NULL. So, in this case, we don't even have any actual credentials to use.
Because they are saved as [`CRED_TYPE_DOMAIN_PASSWORD`](https://learn.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentialw). If we try to read them using the [`CredRead`](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreadw) function then we'll get an empty password blob (even when the function …
> Improve credssp credentials handling

- src/ntlm/messages/client/authenticate.rs
- src/ntlm/mod.rs
I'm using this crate to add NTLM support to my SMB 3.1.1 client I'm developing.
The session_key is used as part of the calculation of the signing key. See this page for details https://learn.microsoft.com/en-us/archive/blogs/openspecification/smb-2-and-smb-3-security-in-windows-10-the-anatomy-of-signing-and-cryptographic-keys
This pull request stashes the session_key that was used in the Ntlm struct, and provides access to it with an accessor function.
> Store and give access to session_key in Ntlm

- Cargo.lock
- Cargo.toml
- examples/client.rs
- ffi/src/macros.rs
- ffi/src/sec_handle.rs
- src/credssp/mod.rs
- src/credssp/sspi_cred_ssp/mod.rs
- src/generator.rs
- src/kerberos/config.rs
- src/kerberos/mod.rs
- src/lib.rs
- src/negotiate.rs
- src/network_client.rs
- src/ntlm/mod.rs
- src/pku2u/mod.rs
- tests/common.rs
- tools/wasm-testcompile/src/lib.rs
Allow SSPI-rs to be completly IO-free, yield the IO operation back to the caller using generator. Hence can be used in the browser.
> [ARC-144] Replace Network Client with Generator Enumerator 

- src/ntlm/messages/client/authenticate.rs
- src/ntlm/messages/client/negotiate.rs
- src/ntlm/mod.rs
1) NTLM flags now allow to disable signing and sealing
2) MIC is now properly generated if key exchange is disabled (such as the case of disabled sealing)
3) NTLM DecryptMessage now supports STREAM decoding
> Ntlm fixes for disabled sealing and signing

- Cargo.lock
- Cargo.toml
- examples/client.rs
- examples/server.rs
- ffi/Cargo.toml
- ffi/src/sec_handle.rs
- proptest-regressions/auth_identity.txt
- src/auth_identity.rs
- src/credssp/mod.rs
- src/credssp/ts_request/test.rs
- src/kerberos/config.rs
- src/kerberos/mod.rs
- src/lib.rs
- src/negotiate.rs
- src/ntlm/config.rs
- src/ntlm/messages/client/negotiate.rs
- src/ntlm/messages/computations/test.rs
- src/ntlm/messages/test.rs
- src/ntlm/mod.rs
- src/pku2u/config.rs
- src/pku2u/mod.rs
- tests/common.rs
- tools/wasm-testcompile/src/lib.rs
- When appropriate, "hostname" was renamed into "client_computer_name"
- Likewise, "Kerberos::url" has been renamed to "Kerberos::kdc_url" and the meaning of the field has been documented (KDC url vs KKDCP url)
- A wrapper around username is exposed to the library user to make it clear that there are different formats:
- User Principal Name (UPN)
- Down-Level Logon Name
Convenience functions are provided to help the user building
proper usernames.
> refactor: clarify naming of user-facing options

- src/credssp/mod.rs
This PR is currently for discussion only. we could hard code the flag in CredSSP, but might not be desired. 
This fixes problem in [IronRDP PR, Enable Kerberos](https://github.com/Devolutions/IronRDP/pull/260).
The changes will force CredSSP to sign and seal the message, which allows it to have the same behavior as before
> Fix: NTLM not working in IronRDP, Add Flag to enforce sign and seal

- Cargo.toml
- src/dns.rs
In some cases (e.g. when using async IO, like TCP connection) resolving DNS queries for KDC will block when used in `tokio::spawn`-ed task. AFAICT this happens because we block thread that is used by IO and timers.
This change fixes that with use `block_in_place` so the thread we're on will be marked by tokio as blocked and other task will be moved to the new one.
> Fix `execute_future` not working with `tokio::spawn`

- src/negotiate.rs
When the first time InitializeSercurityContext is called for negotiate, the variable `self.auth_identity` is always None, but latter used when switching to NTLM or PKU2U, which of course will not work since it is None. Fixed the problem so Negotiate could properly fallback to NTLM with authentication information from the builder.
> Fix Negotiate failure to fallback to NTLM

- src/kerberos/mod.rs
Hi,
In this pull request, I fixed the issue mentioned here: https://github.com/Devolutions/sspi-rs/pull/206#discussion_r1480849938 
During the issue investigation, I noticed that authentication works with all flags except the `GSS_C_DELEG_FLAG` one. It didn't seem related to the smart card authentication stuff. I tested the authentication with password-based logon and got the same error. So it's not related to the login type.
Then I reread the RFC that contains this flag explanation. [RFC 4121: Section 4.1.1:  Authenticator Checksum](https://datatracker.ietf.org/doc/html/rfc4121#section-4.1.1.1):
> The length of the checksum field MUST be at least 24 octets when GSS_C_DELEG_FLAG is not set,
> and at least 28 octets plus Dlgth octets when GSS_C_DELEG_FLAG is set.
Our authenticator checksum …
> Fix Kerberos ApReq Authenticator Checksum Flags

- ffi/src/sspi/sec_winnt_auth_identity.rs
- ffi/src/sspi/utils.rs
- ffi/src/utils.rs
Hi,
In this pull request, I've fixed username handling during the smart card logon.
The problem was in the null characters at the end of the username buffer. We had a similar situation during the password-based logon: https://github.com/Devolutions/sspi-rs/blob/winscard-rs-impl/ffi/src/sspi/sec_winnt_auth_identity.rs#L645-L646
> Fix username handling in FFI during smart card logon

- .github/workflows/build-native.yml
- .github/workflows/ci.yml
- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
The first release featuring the emulated WinSCard support. I also modified the CI to enable the `scard` feature.
> chore(dotnet): prepare for 2023.15.2.0

- examples/client.rs
- ffi/src/sspi/common.rs
- ffi/src/sspi/sec_handle.rs
- src/builders/acq_cred_handle.rs
- src/credssp/mod.rs
- src/credssp/sspi_cred_ssp/mod.rs
- src/credssp/sspi_cred_ssp/tls_connection.rs
- src/kerberos/mod.rs
- src/lib.rs
- src/negotiate.rs
- src/ntlm/mod.rs
- src/ntlm/test.rs
- src/pku2u/mod.rs
- src/utils.rs
- tests/common.rs
Hi,
In this pull request, I have fixed the memory leak during message decryption.
According to the [MSDN](https://learn.microsoft.com/en-us/windows/win32/secauthn/decryptmessage--schannel):
> The encrypted message is decrypted in place, overwriting the original contents of its buffer.
Our previous implementation had allocated new buffers for the decrypted data. It had caused a memory leak because the caller didn't expect new allocations. This problem is fixed by introducing a special `DecryptBuffer` type that uses only mutable references to the provided buffers without any vectors and data cloning.
Note. I suggest refraining from paying a lot of attention to the `tls_connection` module, as I have implemented changes to the decryption process in the upcoming pull request.
> fix(ffi): memory leak during message decryption

- examples/client.rs
- ffi/src/sspi/common.rs
- ffi/src/sspi/utils.rs
- src/credssp/mod.rs
- src/credssp/sspi_cred_ssp/mod.rs
- src/credssp/sspi_cred_ssp/tls_connection.rs
- src/decrypt_buffer.rs
- src/kerberos/mod.rs
- src/lib.rs
- src/ntlm/test.rs
- src/pku2u/mod.rs
- src/utils.rs
- tests/common.rs
Hi,
In this pull request, I have fixed the partial TLS packets decryption.
_Note._ Under the _"partial TLS packet"_ term I mean buffers that contain only some part of the TLS packet. For example, the first 130 bytes, where the full TLS packet is 240.
There can be a situation when `mstsc` can pass only some part of the TLS packet as an input buffer. Previously, we passed such buffers to the `rustls` and were waiting for the rest on the next decrypt function call. But after such n-step packet decryption, we may get a situation when the decrypted data buffer is larger than the encrypted one. It makes it impossible to properly return all decrypted data. Now, the `sspi-rs` behaves as the original `SChannel`:
In a case when it gets the partial TLS message, it'll return `SECBUFFER_MISSING` with …
> fix(sspi): partial TLS buffers decryption

- Cargo.lock
- Cargo.toml
- ffi/dotnet/Devolutions.Sspi/Devolutions.Sspi.csproj
- sspi -> 0.12.0
- winscard -> 0.1.0
- Devolutions.Sspi -> 2024.3.15.0
> chore(release): prepare publishing

- crates/winscard/Cargo.toml
We can’t publish the crate without this key.
> chore(scard): add description key to the manifest

- Cargo.lock
- Cargo.toml
- ffi/Cargo.toml
- ffi/src/sspi/sec_handle.rs
- ffi/src/sspi/sec_winnt_auth_identity.rs
- src/cert_utils.rs
- src/pku2u/cert_utils/win_extraction.rs
This replaces the remaining uses of winapi as per https://github.com/Devolutions/sspi-rs/issues/174. 
I ran the tests with the features `scard,tsssp` enabled since some of the replaced calls are behind these features.
> refactor: replace remaining uses of winapi with windows_sys

- Cargo.lock
- crates/winscard/Cargo.toml
- crates/winscard/src/env.rs
- crates/winscard/src/lib.rs
- crates/winscard/src/scard_context.rs
Hi,
In this pull request, I've improved the environment variables' names and `SmartCardInfo` creation.
The following variable names have been renamed:
* `WINSCARD_PIN` -> `WINSCARD_SMARTCARD_PIN`.
* `WINSCARD_CERT_PATH` -> `WINSCARD_CERTIFICATE_FILE_PATH`.
* `WINSCARD_CONTAINER` -> `WINSCARD_SMARTCARD_CONTAINER_NAME`.
* `WINSCARD_READER` -> `WINSCARD_SMARTCARD_READER_NAME`.
The following variable names have been introduced:
* `WINSCARD_CERTIFICATE_FILE_DATA`: contains the base64 ASN1 DER certificate. Note: We don't support certificate chains in the emulated smart card (yet I hope), so we expect this env var to contain exactly one certificate. [Certificate example](https://crypto.qkation.com/asn1/?asn1=308205853082046da00302010202131c0000000431084fac18de9ae3000000000004300d06092a864886f70d0 …
> winscard: Improve environment variables and smart card info creation

- ffi/src/sspi/sec_winnt_auth_identity.rs
- src/kerberos/mod.rs
Hi,
In this PR I've made two main changes:
* Fixed the credentials handling in the CredSSP module when using `ClearTextPassword` to specify the password. Now we can connect to the RDP server using only the `.rdp` file without any credentials prompts.
* Improved the error handling in the Kerberos implementation.
> Fix CredSSP credentials handling when using `ClearTextPassword` to specify the password

- crates/ffi-types/src/common.rs
- ffi/src/winscard/scard_context.rs
Hi,
In this pull request, I've fixed the `SCardAccessStartedEvent` function implementation.
Previously, we returned hardcoded value from the `SCardAccessStartedEvent` function. Unfortunately, it causes an error sometimes when using `sspi.dll` in `mstsc.exe`. This problem was fixed by introducing one global event for the entire process. We create one signaled event using Windows API and return a handle to it from the `SCardAccessStartedEvent` function. In such a way we tell that our emulated smart card is always ready. Moreover, this is a reason why we didn't use any reference counters as the original API assumes.
closes #230
> Correctly implement SCardAccessStartedEvent

- src/utils.rs
I am really sorry!
I forget to remove the println! while debugging, removed the println!, I'll create another PR so the linter won't ignore it.
> fix:remove left over println

- Cargo.toml
- ffi/Cargo.toml
- ffi/src/sspi/common.rs
- src/kerberos/mod.rs
- src/pku2u/mod.rs
- src/utils.rs
Hi,
In this pull request, I fixed the `SECBUFFER_STREAM` buffer handling.
This is how it works: 
I've explored the `SECBUFFER_STREAM` buffer usage and discovered that it is only used to pass the data to the decrypt function. Moreover, as I understand, it never changes its size and pointer location.
The sspi takes the inner buffer from the `Stream` decrypt buffer, writes data into it, and then assigns it to the `Data` decrypt buffer. Thus, after the decryption, the `Stream` decrypt buffer will be empty, and `Data` will contain decrypted data. But during the data copying on the FFI layer, we skip the `SECBUFFER_STREAM` buffer. So, we'll have resulting buffers the same as in the Windows SSPI.
Also, I added a test in the `ffi` crate that calls the `DecryptMessage` functions and expects the …
> Improve `SECBUFFER_STREAM` buffer handling

- .github/workflows/ci.yml
- ffi/src/lib.rs
- src/utils.rs
waiting for #235 to be merged first, to prevent people from the same mistake.
> chore(ci): disallow println std in sspi lints

- ffi/src/sspi/sec_winnt_auth_identity.rs
- ffi/src/utils.rs
Hi,
In this pull request I improved the smart card credentials handling.
cc @awakecoding
> Improve smart card credentials handling

- crates/ffi-types/src/winscard/functions.rs
- crates/winscard/src/lib.rs
- crates/winscard/src/winscard.rs
- ffi/Cargo.toml
- ffi/src/winscard/mod.rs
- ffi/src/winscard/scard.rs
- ffi/src/winscard/system_scard/card.rs
- ffi/src/winscard/system_scard/context.rs
- ffi/src/winscard/system_scard/macros.rs
- ffi/src/winscard/system_scard/mod.rs
Hi,
In this pull request, I've implemented the system-provided smart card support. Now we can call system API to access system-provided smart cards.
I've also implemented dynamic `winscard.dll` loading. We can't always use the `winscard-sys` crate, because if the `winscard.dll` is hooked (in the case of [MsRdpEx](https://github.com/Devolutions/MsRdpEx)), then the `winscard-sys` will just redirect calls to our library and we'll get a stack overflow.
> System-provided smart card implementation

- crates/winscard/src/lib.rs
- crates/winscard/src/scard_context.rs
- ffi/src/lib.rs
- ffi/src/sspi/sec_winnt_auth_identity.rs
- ffi/src/utils.rs
- ffi/src/winscard/buf_alloc.rs
- ffi/src/winscard/macros.rs
- ffi/src/winscard/pcsc_lite/mod.rs
- ffi/src/winscard/scard.rs
- ffi/src/winscard/scard_context.rs
- ffi/src/winscard/scard_handle.rs
- ffi/src/winscard/system_scard/context.rs
- ffi/src/winscard/system_scard/mod.rs
- src/utils.rs
Hi,
In this PR, I've improved the WinSCard FFI layer. According to my plan, this iteration's last intermediate PR. I'll perform some additional dev testing when the PR is merged.
* I moved the `clippy::undocumented_unsafe_blocks` lint to the `ffi/winscard` module lever instead of `ffi/winscard/system_scard`. Now all winscard-related code is checked.
* Refactored the code and removed all panics.
* Improved the memory management. A detailed explanation is below.
Many winscard functions can treat the resulting data differently based on the input parameters.
* When the input data pointer is `NULL`, we should write out data len in the input data len pointer.
* When the input data length pointer value is `SCARD_AUTOALLOCATE`, we should allocate memory by ourselves, cast the output data pointer …
> Winscard FFI improvements

- ffi/src/winscard/buf_alloc.rs
- ffi/src/winscard/scard_handle.rs
Hi,
After the last intermediate PR I did some dev testing to check if everything is sill working. I found a small mistake and fixed it in this PR.
Also, I've improved the logging a little bit.
> Fix null check in `save_out_buf` and `save_out_buf_wide` functions

- Cargo.lock
- crates/ffi-types/src/common.rs
- crates/ffi-types/src/winscard/functions.rs
- crates/winscard/Cargo.toml
- crates/winscard/src/lib.rs
- crates/winscard/src/scard.rs
- crates/winscard/src/scard_context.rs
- crates/winscard/src/winscard.rs
- ffi/Cargo.toml
- ffi/src/lib.rs
- ffi/src/sspi/sec_winnt_auth_identity.rs
- ffi/src/utils.rs
- ffi/src/winscard/buf_alloc.rs
- ffi/src/winscard/macros.rs
- ffi/src/winscard/mod.rs
- ffi/src/winscard/pcsc_lite/functions.rs
- ffi/src/winscard/pcsc_lite/mod.rs
- ffi/src/winscard/scard.rs
- ffi/src/winscard/scard_context.rs
- ffi/src/winscard/scard_handle.rs
- ffi/src/winscard/system_scard/card.rs
- ffi/src/winscard/system_scard/context.rs
- ffi/src/winscard/system_scard/macros.rs
- ffi/src/winscard/system_scard/mod.rs
- src/cert_utils.rs
- src/lib.rs
- src/smartcard.rs
- src/utils.rs
Hi,
In this PR I've implemented the system provided smart cards support. Now the user can use real smart cards using our library as well as emulated ones.
More information you can read in those pull requests descriptions:
* https://github.com/Devolutions/sspi-rs/pull/246
* https://github.com/Devolutions/sspi-rs/pull/248
* https://github.com/Devolutions/sspi-rs/pull/249
* https://github.com/Devolutions/sspi-rs/pull/250
* https://github.com/Devolutions/sspi-rs/pull/251
1. The `sspi` loads all additional libraries (like `libpcsclite` or `winscard.dll`) in the runtime. Related discussion: https://github.com/Devolutions/sspi-rs/pull/246#discussion_r1621256727.
2. The system scards implementation is hidden under the `WinScard` and `WinScardContext`. The system scard is just another …
> System provided scards support

- Cargo.lock
- examples/client.rs
- examples/server.rs
- ffi/Cargo.toml
- ffi/src/sspi/credentials_attributes.rs
- ffi/src/sspi/sec_handle.rs
- ffi/src/sspi/utils.rs
Hi,
In this PR, I've updated the `Cargo.lock`. I didn't update any dependencies explicitly in any `Cargo.toml` file. I just regenerated the `Cargo.lock` file.
The only purpose of this PR is to be able to compile the library with nightly Rust. One of the dependencies was failing to compile before this update:
We want to run FFI tests with [Miri](https://github.com/rust-lang/miri). But Miri requires a nightly toolchain.
> build(deps): update Cargo.lock

- Cargo.lock
- Cargo.toml
- crates/ffi-types/Cargo.toml
- crates/winscard/Cargo.toml
- ffi/Cargo.toml
- fuzz/Cargo.toml
- tools/sspi-ffi-attacker/Cargo.toml
- tools/wasm-testcompile/Cargo.toml
The new dependencies are induced by internal refactor of libraries, but duplicates are mostly avoided.
Remaining duplicates can be avoided by updating picky dependencies, and windows-related crates.
cc @TheBestTvarynka, do you think you could look into updating the windows crates?
> chore(deps): update dependencies

- .github/workflows/build-native.yml
- .github/workflows/ci.yml
- Cargo.toml
- src/credssp/sspi_cred_ssp/mod.rs
- src/credssp/sspi_cred_ssp/tls_connection.rs
I don’t know why, but this PR got merged even though CI wasn’t green: https://github.com/Devolutions/sspi-rs/pull/261
> build: fix Windows build for newer rustls

- Cargo.lock
- Cargo.toml
- src/auth_identity.rs
- src/credssp/ts_request/mod.rs
- src/kerberos/mod.rs
- src/kerberos/pa_datas.rs
- src/lib.rs
- src/negotiate.rs
- src/smartcard.rs
This PR aims to move code that doesn't depend on real smart card reader out of `scard` feature.
> refactor: move hardware-independent code out of scard feature

- src/credssp/sspi_cred_ssp/cipher_block_size.rs
- src/credssp/sspi_cred_ssp/mod.rs
- src/credssp/sspi_cred_ssp/tls_connection.rs
- src/credssp/ts_request/mod.rs
Hi,
In this pull request, I've improved the cipher block size extraction. Related comment: https://github.com/Devolutions/sspi-rs/pull/263#discussion_r1671978937 
I browsed the new API and tried different methods. Conclusion: there is no good way of extracting the cipher block size. So, I decided to take supported cipher suites in SChannel (Windows 10/11) + popular ones and list all of them in one `match`.
Such a code is more explicit and easy to maintain.
> fix(sspi): tls connection: improve cipher block size calculation

- ffi/src/sspi/sec_winnt_auth_identity.rs
Hi,
In this PR, I've fixed the scared pk handling. Now we convert it to UTF-8 as other credentials buffers.
We encountered this problem after this PR: https://github.com/Devolutions/sspi-rs/pull/260/files#diff-40e9fc919e63077bc0b25847ecf6746216d0438cd3808de82d713a7cc71bce56R753-R756 
cc @awakecoding
> Fix smart card private key handling

- .github/workflows/build-native.yml
- Cargo.lock
- Cargo.toml
- ffi/Cargo.toml
- src/credssp/sspi_cred_ssp/mod.rs
- src/kerberos/mod.rs
- src/lib.rs
- src/network_client.rs
- src/pku2u/mod.rs
- src/rustls.rs
The aws-lc-rs backend is enabled by default.
> fix(sspi): make TLS backend configurable via features

- .github/workflows/build-native.yml
The Android 19 toolchain is not included anymore, so we bump the minimum supported version to Android 21 for i686 (x86) architecture.
> ci(nuget): fix build for Android x86

- Cargo.lock
- crates/ffi-types/src/common.rs
- crates/ffi-types/src/winscard/functions.rs
- crates/winscard/src/env.rs
- crates/winscard/src/lib.rs
- crates/winscard/src/scard_context.rs
- crates/winscard/src/winscard.rs
- ffi/Cargo.toml
- ffi/src/winscard/buf_alloc.rs
- ffi/src/winscard/pcsc_lite/functions.rs
- ffi/src/winscard/pcsc_lite/mod.rs
- ffi/src/winscard/scard_context.rs
- ffi/src/winscard/scard_handle.rs
- ffi/src/winscard/system_scard/card.rs
- ffi/src/winscard/system_scard/context.rs
- ffi/src/winscard/system_scard/macros.rs
Hi,
In this PR I've fixed the smart card auth for Linux and macOS. Now we can use smart card auth with FreeRDP on Linux and macOS.
Originally, we planned to link with `pcsc-lite` on Linux and macOS. But it turned out that the `pcsc-lite` doesn't work well on macOS. We have tried to overcome it in a few ways but failed. After all tries we decided to link with the `PCSC.framework`. We adjusted the bindings and managed to make it work.
To use the smart card auth you need to perform some configurations.
1. **Kerberos.** You need to write your own `krb.conf` or ask your sysadmin to provide you with one. It should look like this (replace domain, CA cert file path, and realm with your ones):
```conf
[libdefaults]
default_realm = TBT.COM
[realms]
TBT.COM = {
admin_server = WIN-956CQOSSJTF.tbt.com …
```
> Fix Linux/macOS system smart card support

- src/security_buffer.rs
When performing an LDAP connection using SSPI-RS the Encryption function was failing if sending a Padding type security buffer. I added the padding type and the encryption method now works again.
> fix: added padding buffer type for encryption function

- src/security_buffer.rs
Since `SecurityBuffer` is a type from our public API, and that we may add support for more types in the future, it’s better to annotate it with `#[non_exhaustive]` for now.
Otherwise adding a new variant is a breaking change.
cc @TheBestTvarynka
> fix(sspi): add #[non_exhaustive] on SecurityBuffer

- ffi/src/winscard/system_scard/card.rs
This problem was added in #294 . I don't know why CI didn't cache it. Maybe the `--scard` feature wasn't turned on during compilation on macOS/Linux
> fix(ffi): compilation with `scard` feature on macOS

- .github/workflows/build-native.yml
- .github/workflows/ci.yml
- ffi/Cargo.toml
- ffi/src/winscard/pcsc_lite/mod.rs
- ffi/src/winscard/scard.rs
- ffi/src/winscard/scard_context.rs
- ffi/src/winscard/system_scard/context.rs
- ffi/src/winscard/system_scard/mod.rs
> build(ffi): include the scard feature by default

- crates/winscard/src/lib.rs
- crates/winscard/src/scard.rs
- crates/winscard/src/winscard.rs
- ffi/src/sspi/common.rs
- ffi/src/sspi/sec_handle.rs
- ffi/src/sspi/sec_winnt_auth_identity.rs
- ffi/src/utils.rs
- src/kerberos/config.rs
- src/lib.rs
- src/security_buffer.rs
Hi,
In this PR I've fixed the memory corruption error in the `AcquireCredentialsHandleA/W` functions. The user can safely pass the `null`/empty credentials strings.
Also, I covered such cases with tests.
> Fix memory corruption in the `AcquireCredentialsHandleA/W` functions

- Cargo.toml
We can’t publish `sspi` otherwise.
cc @TheBestTvarynka
> build: specify version for winscard dependency

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- ffi/Cargo.toml
We have a special logic for DNS resolving when targetting macOS.
This PR is also fixing a problem in our feature set causing the compilation to fail on macOS when the `dns_resolver` feature is not enabled on macOS.
> ci: do not enable dns_resolver feature for macOS

- .github/workflows/build-native.yml
- .github/workflows/ci.yml
The macOS 12 runner image will be removed by December 3rd, 2024
> ci: update macos-12 runners to macos-14

- src/ntlm/messages/server/complete_authenticate.rs
Fixes #349 by storing session key when `fn complete_authenticate` is called
> fix: store session key when using Ntlm as a server

- crates/dpapi/src/crypto/mod.rs
Hi,
I fixed DPAPI blob decryption in this PR.
Previously, we assumed that the AES IV is always encoded as `AesParameters::InitializationVector`. But recently we discovered that it also can be encoded as `AesParameters::AuthenticatedEncryptionParameters`. It depends on the blob creation process.
> fix(dpapi): AES IV extraction during decryption;

- crates/dpapi/src/client.rs
- crates/dpapi/src/rpc/auth.rs
- ffi/build.rs
- src/lib.rs
- src/negotiate.rs
Hi,
I refactored the DPAPI implementation a bit: now it uses Negotiate module instead of hardcoded Kerberos configuration. I added corresponding comments in the code.
> feat(dpapi): use Negotiate module instead of hardcoded Kerberos

- src/kerberos/mod.rs
Hi,
I fixed Kerberos LDAP auth in this PR. The problem was in the invalid sequence number in MIC token. The most surprising thing is that the RDP authentication worked even without this fix.
> fix(kerberos): set correct seq number in MIC token

- crates/dpapi/src/rpc/auth.rs
- crates/dpapi/src/rpc/client.rs
- src/kerberos/mod.rs
Hi,
I fixed the NTLM RPC auth in this PR. Explanation:
Our Kerberos implementation has parts of SPNEGO and GSS API tokens inside. The first phase of the Kerberos implementation is called `Negotiate`: https://github.com/Devolutions/sspi-rs/blob/bda97ded7807e15f92ad796f881f85ef27839d96/src/kerberos/mod.rs#L109 + https://github.com/Devolutions/sspi-rs/blob/bda97ded7807e15f92ad796f881f85ef27839d96/src/kerberos/mod.rs#L800-L832. And we don't need it during the RPC auth. So, we just decided to call the `initialize_security_context` method twice and just ignore the first call result: https://github.com/Devolutions/sspi-rs/blob/bda97ded7807e15f92ad796f881f85ef27839d96/crates/dpapi/src/rpc/client.rs#L350-L354.
But it works only when `Kerberos` or `Negotiate(Kerberos)` security package is used. …
> fix(dpapi): NTLM RPC auth

- Cargo.toml
- tests/sspi/client_server/mod.rs
The other tests can be run even without the network_client feature enabled.
> test(sspi): network_client is only required for a subset of the tests

- crates/dpapi/src/client.rs
- crates/dpapi/src/rpc/auth.rs
- src/credssp/mod.rs
- src/credssp/sspi_cred_ssp/mod.rs
- src/credssp/ts_request/mod.rs
- src/kdc.rs
- src/negotiate.rs
- src/ntlm/mod.rs
- src/pku2u/mod.rs
cc @TheBestTvarynka 
I missed this pattern. It’s also possible to change the event level without changing the span level, but it makes sense to not create info-level spans since we are not supposed to log at info-level (although this can be useful for warnings that will inherit the info-level span.
> fix: do not log at info-level return values

- .github/dependabot.yml
more context: https://github.com/Devolutions/sspi-rs/pull/441#discussion_r2128800079
> ci(dependabot): remove `winreg` from dependabot configuration

- src/kerberos/client/generators.rs
I have upgraded `sspi` to version 0.15.11 after the merge of my [last PR](https://github.com/Devolutions/sspi-rs/pull/447).
Testing the new code today against my Active Directory setup, I had a general DER error:
```
SspiError(Error { error_type: InvalidToken, description: "ASN1 DER error: InvalidData", nstatus: None })
```
Sniffing the session, and more specifically, taking a look at the token from `sspi`:
Seems like the error originates in an invalid DER-encoded kerberos token, that later causes the server to respond with a generic kerberos error.
I have checked out an earlier revision of my code, and it was working properly. A Quick Look at my `sspi` usage seemed very similar to the up-to-date one, so I tried reverting package versions and it was all working.
From there, I narrowed …
> fix: invalid Kerberos token DER encoding

- src/kerberos/client/mod.rs
- src/kerberos/server/generators.rs
- src/kerberos/server/mod.rs
- src/kerberos/utils.rs
Hi,
I fixed Kerberos server MIC token generation and validation. I discovered these problems during dev-testing using `mstscex`.
> fix(sspi): Kerberos server MIC token generation and validation

- src/kerberos/mod.rs
- src/kerberos/tests.rs
Hi,
I fixed Kerberos server WRAP token generation and validation. I discovered these problems during dev-testing using `mstscex`.
> fix(sspi): Kerberos server WRAP token generation and validation

- crates/ffi-types/src/winscard/functions.rs
- crates/ffi-types/src/winscard/mod.rs
- crates/winscard/src/scard.rs
- crates/winscard/src/tlv_tags.rs
- crates/winscard/src/winscard.rs
- ffi/src/winscard/mod.rs
- ffi/src/winscard/pcsc_lite/functions.rs
- ffi/src/winscard/pcsc_lite/mod.rs
- ffi/src/winscard/scard.rs
- ffi/src/winscard/scard_handle.rs
- ffi/src/winscard/system_scard/card.rs
- ffi/src/winscard/system_scard/context.rs
- ffi/src/winscard/system_scard/mod.rs
Hi,
I this PR I fixed incorrect [`SCARD_IO_REQUEST`](https://learn.microsoft.com/en-us/windows/win32/secauthn/scard-io-request) usage.
The `SCARD_IO_REQUEST` structure contains protocol-specific information. The active smart card communication protocol is negotiated during [`SCardConnect`](https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnectw) (see `pdwActiveProtocol` parameter).
All `SCARD_IO_REQUEST`s are predefined in WinSCard/PCSC-lite and we can obtain handle to them using the following names `g_rgSCardT0Pci`/`g_rgSCardT1Pci`/`g_rgSCardRawPci`.
So, when calling system provided smart card API via WinSCard/PCSC, we should use the predefined `SCARD_IO_REQUEST` based on the negotiated active protocol.
> fix(winscard): incorrect `SCARD_IO_REQUEST` usage

- ffi/src/sspi/sec_winnt_auth_identity.rs
Hi,
Previously, only FQDN usernames (username@domain) were suitable for smart card logon. I added support for regular credentials (when username and domain are separate parameters) in smart card credentials handling.
In short, because of FreeRDP. More comprehensive explanation:
Unfortunately, FreeRDP does not split FQDN username into username and domain parts before sending credentials in the last CredSSP TsRequest message. Example of bad credentials:
([link to bad credentials](https://crypto.qkation.com/asn1/?asn1=3082012ca003020102a18201230482011f3082011ba00e040c310032003300340035003600a181de3081dba003020101a2320430590075006200690063006f00200059007500620069004b006500790020004600490044004f002b004300430049004400a34a0448660061003100330038003200370063002d0033003000350030002d00310037006300620 …
> fix(ffi): accept regular credentials for smart card logon

- crates/winscard/src/scard.rs
Hi,
Recently I noticed that we have a failing test in the `winscard` crate. This PR fixes it.
_Note: I was able to reproduce the issue only when running `cargo test` with the `--all` arg._
> fix(winscard): general authenticate command validation
